services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: loan_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - loan_management_pgdata:/var/lib/postgresql/data

volumes:
  loan_management_pgdata:
